server:
    port: 8080
    context-path: /what
base:
    address: 111.111.111.11
    username: root
    password: rrrr
    content: "${base.address}"
config:
  baseDb:
    url: jdbc:mysql:///test2
    username: root2
    password: 2345