server:
  port: 8081
  context-path: /whataaa
config:
  baseDb:
    url: jdbc:mysql:///test
    username: root1
    password: 1234
spring:
  mvc:
    view:
      prefix: /pages/jsp/
      suffix: .jsp
    date-format: yyyy-MM-dd
    throw-exception-if-no-handler-found: true
#  jta:
#    transaction-manager-id: transactionManager 
  resources:
    static-locations:
    - /pages/static
    - /pages/css
    - /pages/jsp/
#mybatis:
#  mapper-locations:
#  - classpath:com\sf\mapper\UserMapper.xml
#  type-aliases-package: com.sf.model
# 这里甚至不需要指定mapper文件。
