server:
  port: 8081
  context-path: /whataaa
base:
  address: localhost
  username: root
  password: fhfh
  content: ${base.address}
spring:
  datasource:
    url: jdbc:mysql:///
    username: root
    password: fhfh
    driver-class-name: com.mysql.jdbc.Driver