package com.sf.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.idUser
     *
     * @mbg.generated Fri Jan 06 00:19:04 CST 2017
     */
    private Integer iduser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Fri Jan 06 00:19:04 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbg.generated Fri Jan 06 00:19:04 CST 2017
     */
    private Date birthday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.idUser
     *
     * @return the value of user.idUser
     *
     * @mbg.generated Fri Jan 06 00:19:04 CST 2017
     */
    public Integer getIduser() {
        return iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.idUser
     *
     * @param iduser the value for user.idUser
     *
     * @mbg.generated Fri Jan 06 00:19:04 CST 2017
     */
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Fri Jan 06 00:19:04 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Fri Jan 06 00:19:04 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * @mbg.generated Fri Jan 06 00:19:04 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * @mbg.generated Fri Jan 06 00:19:04 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
}